# Generated by Django 3.1.1 on 2022-04-07 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Providers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Business name')),
                ('contact', models.CharField(max_length=30, verbose_name='Contact person')),
                ('email', models.CharField(max_length=50)),
                ('phone', models.CharField(max_length=10, verbose_name='Phone number')),
            ],
        ),
    ]
