# Generated by Django 3.1.1 on 2022-04-15 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='embed_link',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
