# Generated by Django 3.1.1 on 2022-04-08 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0004_client'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='partner_email',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='client',
            name='partner_name',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='client',
            name='partner_phone',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='client',
            name='phone',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
