# Generated by Django 3.1.1 on 2022-04-08 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0005_auto_20220408_0929'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='address',
            field=models.CharField(max_length=50, null=True, verbose_name='street address'),
        ),
        migrations.AddField(
            model_name='client',
            name='city',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='client',
            name='state',
            field=models.CharField(max_length=2, null=True),
        ),
        migrations.AddField(
            model_name='client',
            name='zip',
            field=models.CharField(max_length=9, null=True, verbose_name='zip code'),
        ),
    ]
