# Generated by Django 3.1.1 on 2022-04-08 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0006_auto_20220408_0940'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='due_date',
            field=models.DateField(null=True),
        ),
    ]
