# Generated by Django 3.1.1 on 2022-04-08 14:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0008_connected_clients_invoices'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Invoices',
            new_name='Invoice',
        ),
        migrations.RenameModel(
            old_name='Providers',
            new_name='Provider',
        ),
        migrations.RenameModel(
            old_name='Videos',
            new_name='Video',
        ),
    ]
